### ISSUE TITLE
metric is already registered

### ISSUE THREAD

**Issue by mattparkes** [faceair/VictoriaLogs#2]
I just cloned `master` and built with `make all` and got the following error:

```
$ bin/vmselect -storageNode 127.0.0.1:8401

panic: BUG: metric "vm_cache_requests_total{type=\"promql/regexp\"}" is already registered

goroutine 1 [running]:
github.com/VictoriaMetrics/metrics.(*Set).mustRegisterLocked(0xc000146300, 0xa3b576, 0x2d, 0xae3120, 0xc00012c070)
	/root/go/pkg/mod/github.com/!victoria!metrics/metrics@v1.12.3/set.go:450 +0x2ae
github.com/VictoriaMetrics/metrics.(*Set).registerMetric(0xc000146300, 0xa3b576, 0x2d, 0xae3120, 0xc00012c070)
	/root/go/pkg/mod/github.com/!victoria!metrics/metrics@v1.12.3/set.go:433 +0xda
github.com/VictoriaMetrics/metrics.(*Set).NewGauge(0xc000146300, 0xa3b576, 0x2d, 0xc000110ea0, 0x0)
	/root/go/pkg/mod/github.com/!victoria!metrics/metrics@v1.12.3/set.go:250 +0x89
github.com/VictoriaMetrics/metrics.NewGauge(...)
	/root/go/pkg/mod/github.com/!victoria!metrics/metrics@v1.12.3/gauge.go:24
github.com/VictoriaMetrics/VictoriaLogs/lib/logql.glob..func1(0x7ff8000000000001)
	/usr/share/victorialogs/VictoriaLogs/lib/logql/regexp_cache.go:36 +0xbe
github.com/VictoriaMetrics/VictoriaLogs/lib/logql.init()
	/usr/share/victorialogs/VictoriaLogs/lib/logql/regexp_cache.go:46 +0xa39
root@victorialogs-0:/usr/share/victorialogs/VictoriaLogs#
```

To fix it, I had to do the following in `lib/logql/regexp_cache.go`:
```
-       "github.com/VictoriaMetrics/metrics"
```
and
```
-       metrics.NewGauge(`vm_cache_requests_total{type="promql/regexp"}`, func() float64 {
-               return float64(rc.Requests())
-       })
-       metrics.NewGauge(`vm_cache_misses_total{type="promql/regexp"}`, func() float64 {
-               return float64(rc.Misses())
-       })
-       metrics.NewGauge(`vm_cache_entries{type="promql/regexp"}`, func() float64 {
-               return float64(rc.Len())
-       })
```
After I did that, it `make all` ran successfully and the binaries appeared in `bin/`.

**Comment by faceair** [comment]
Thanks, I changed the name of the metric.
